import React from 'react';
import type { Metadata } from 'next';
import { TypeScaleTool } from '@/components/TypeScaleTool';
import { Breadcrumbs } from '@/components/Breadcrumbs';
import { JsonLd } from '@/components/JsonLd';

export const metadata: Metadata = {
  title: 'Typography Generator - Modular Type Scale & Hierarchy Calculator',
  description:
    'Calculate harmonious typography scales and modular hierarchies. Export production-ready CSS variables and Tailwind config tokens with musical optical ratios.',
  keywords: [
    'typography generator',
    'type scale generator',
    'modular scale calculator',
    'typography calculator',
    'font hierarchy generator',
    'tailwind font scale',
    'css type scale',
    'modular typography',
  ],
  alternates: {
    canonical: 'https://typefacegen.com/typography-generator',
  },
  openGraph: {
    type: 'website',
    locale: 'en_US',
    url: 'https://typefacegen.com/typography-generator',
    siteName: 'TypefaceGen',
    title: 'Typography Generator - Modular Type Scale & Hierarchy Calculator',
    description:
      'Calculate harmonious typography scales and modular hierarchies. Export production-ready CSS variables and Tailwind config tokens with musical optical ratios.',
    images: [
      {
        url: '/og-image.png',
        width: 1200,
        height: 630,
        alt: 'Typography Scale Generator - TypefaceGen',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: 'Typography Generator - Modular Type Scale & Hierarchy Calculator',
    description:
      'Calculate harmonious typography scales and modular hierarchies. Export production-ready CSS variables and Tailwind config tokens with musical optical ratios.',
    images: ['/og-image.png'],
  },
};

export default function TypographyGeneratorPage() {
  const breadcrumbs = [
    { label: 'Tools', href: '/' },
    { label: 'Type Scale Generator' },
  ];

  const scaleFaqs = [
    {
      question: 'What is a modular type scale?',
      answer:
        'A modular type scale is a sequence of harmonious font sizes generated by multiplying or dividing a base font size (like 16px) by a fixed mathematical ratio—such as 1.25 (Major Third) or 1.333 (Perfect Fourth). This produces consistent, natural visual rhythm across all heading levels.',
    },
    {
      question: 'Which type scale ratio is best for web design?',
      answer:
        'For general marketing websites and blogs, Major Third (1.25) or Minor Third (1.20) provides an ideal balance of distinction and compact density. For dense SaaS dashboards and complex tables, Minor Second (1.067) or Major Second (1.125) prevents oversized headings from consuming limited screen real estate.',
    },
  ];

  return (
    <div className="space-y-8">
      <Breadcrumbs items={breadcrumbs} />
      <JsonLd
        type="tool"
        toolName="TypefaceGen Modular Typography Scale Generator"
        toolDescription="Calculate harmonious typography scales and modular hierarchies. Export production-ready CSS variables and Tailwind config tokens."
        url="https://typefacegen.com/typography-generator"
        breadcrumbs={[
          { name: 'Home', item: 'https://typefacegen.com/' },
          { name: 'Typography Generator', item: 'https://typefacegen.com/typography-generator' },
        ]}
        faqs={scaleFaqs}
      />

      <div className="space-y-1.5 max-w-2xl">
        <h1 className="text-2xl sm:text-4xl font-extrabold tracking-tight text-zinc-950">
          Modular Typography Scale Generator
        </h1>
        <p className="text-xs sm:text-sm text-zinc-500 leading-relaxed">
          Design mathematically harmonious type systems. Select base sizes, explore optical ratios,
          and export instant CSS custom properties and Tailwind configuration tokens.
        </p>
      </div>

      <TypeScaleTool isStandalonePage />

      <section className="pt-6 border-t border-zinc-200 space-y-6 max-w-4xl">
        <div className="space-y-1">
          <h2 className="text-lg font-bold text-zinc-950">
            Why Mathematical Modular Scales Matter
          </h2>
          <p className="text-xs text-zinc-500 leading-relaxed">
            Eliminate arbitrary font sizes by grounding your design hierarchy in mathematical proportions.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 text-xs">
          <div className="p-4 bg-white border border-zinc-200 rounded space-y-1">
            <h3 className="font-bold text-zinc-950">Harmonious Rhythm</h3>
            <p className="text-zinc-600 leading-relaxed">
              Every level in the hierarchy relates by an exact ratio, instilling subconscious order.
            </p>
          </div>
          <div className="p-4 bg-white border border-zinc-200 rounded space-y-1">
            <h3 className="font-bold text-zinc-950">Token Velocity</h3>
            <p className="text-zinc-600 leading-relaxed">
              Export tokens directly to Tailwind or CSS custom properties for single-source-of-truth syncing.
            </p>
          </div>
          <div className="p-4 bg-white border border-zinc-200 rounded space-y-1">
            <h3 className="font-bold text-zinc-950">Responsive Scaling</h3>
            <p className="text-zinc-600 leading-relaxed">
              Adjust the root base size (14px mobile vs 16px desktop) and the entire scale adapts fluidly.
            </p>
          </div>
        </div>
      </section>
    </div>
  );
}
